#!/bin/bash

echo "##################################################"
date

ls /var/run/httpd/httpd.pid &> /dev/null

if [ $? -eq 0 ]
then
        echo "Httpd Process is Running"
else
        echo "Httpd process is Not Running"
echo " Starting Httpd process"

systemctl start httpd

if [ $? -eq 0 ]
then
        echo "Process started Successfully."
else
        echo " Process Starting Failed. Contact the Linux Admin."
fi
fi
echo "###########################################################"
echo "Thanks - Script by AALAM"


